name: go test

on:
  push:
    branches-ignore:
      - main

jobs:
  gosec:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Run gosec security scanner
        uses: securego/gosec@master
        with:
          args: ./...

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Go lint check
        uses: golangci/golangci-lint-action@v2.5.2

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Cache build dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go fmt check
        run: diff -u <(echo -n) <(gofmt -d ./)

      - name: Run tests
        run: go test ./...
