name: go test

on:
  push:
    branches-ignore:
      - main

jobs:
  gosec:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run gosec security scanner
        uses: securego/gosec@master
        with:
          args: ./...

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go lint check
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go fmt check
        run: diff -u <(echo -n) <(gofmt -d ./)

      - name: Go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run tests
        run: go test ./...
